language: python
python:
  - "2.6"
  - "2.7"
install: "pip install -U -r requirements.txt -r requirements-dev.txt"
after_failure:
  - "test/stop_server.sh"
script:
  - coverage erase
  - "./test/start_server.sh"
  - "python test/test_launcher.py"
  - "./test/stop_server.sh"
  - sleep 5
  - coverage combine
  - coverage report
  - coveralls
sudo: false
