language: python
python:
  - "2.6"
  - "2.7"
install: "pip install -U -r requirements.txt -r requirements-dev.txt"
after_failure:
  - "test/stop_server.sh"
script:
  - coverage erase
  - "test/start_server.sh"
  - ls -al
  - sleep 5
  - "test/stop_server.sh"
  - ls -al
  - sleep 5
  - ls -al
  - coverage combine
  - ls -al
  - coverage report
  - ls -al
  - coveralls
sudo: false
